# Generated by Django 4.1.7 on 2023-03-24 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectadmin', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now=True)),
                ('symptoms', models.CharField(default='', max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('cunsultion_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectadmin.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.patient')),
            ],
        ),
    ]
