# Generated by Django 4.1.7 on 2023-03-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
